Added Prisma ORM Service
xthirtysix/nest-react-app pull request #4
Opened 2022-08-05 09:54 UTC by Bumbeee

- Added `Prisma` to project
- Updated `README.md`

2022-08-05 10:02 UTC, xthirtysix requested changes
Yet prisma service was not implemented. Shall we create a subtask?

2022-08-05 10:04 UTC, xthirtysix commented on prisma/schema.prisma
> +  url      = env("DATABASE_URL")
Let's add a guide for setting `DATABASE_URL` environment variable

2022-08-08 08:30 UTC, Bumbeee commented
@xthirtysix new commits here, can you review it?

2022-08-08 10:03 UTC, xthirtysix approved these changes

2022-08-08 10:03 UTC, merged